name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: abrasumente/riscv-qemu-gcc:latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Cat the README
        run: cat README.md
      - name: Check QEMU version
        run: qemu-system-riscv64 --version