name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: abrasumente/riscv-qemu-gcc:latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Check toolchain version
        run: qemu-system-riscv64 --version && riscv64-unknown-elf-gcc --version
      - name: Make filesystem image
        run: make fs
      - name: Run tests
        run: python3 tester.py